<!DOCTYPE html>



  


<html class="theme-next gemini use-motion" lang="zh-Hans">
<head><meta name="generator" content="Hexo 3.8.0">
  <meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="theme-color" content="#222">









<meta http-equiv="Cache-Control" content="no-transform">
<meta http-equiv="Cache-Control" content="no-siteapp">
















  
  
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css">







<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css">

<link href="/css/main.css?v=5.1.4" rel="stylesheet" type="text/css">


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=5.1.4">


  <link rel="mask-icon" href="/images/logo.svg?v=5.1.4" color="#222">





  <meta name="keywords" content="IT,">










<meta name="description" content="异常概述异常就是Java程序运行过程中出现的错误（通常有不同严重程度）。 异常由来：异常也是现实生活中的一个具体事务，也可以通过Java形式对其进行描述，并封装成对象。其实就是Java对不正常情况进行描述后的对象体现。Java将异常封装成了一个对象。  异常的分类在Java程序设计语言中，异常对象都是派生于Throwable类的一个实例（即所有的异常类都继承于Throwable类）。如果Java中">
<meta name="keywords" content="IT">
<meta property="og:type" content="article">
<meta property="og:title" content="23-异常">
<meta property="og:url" content="http://yoursite.com/2019/04/11/Java语言-23-异常/index.html">
<meta property="og:site_name" content="新世纪Coder战士的博客">
<meta property="og:description" content="异常概述异常就是Java程序运行过程中出现的错误（通常有不同严重程度）。 异常由来：异常也是现实生活中的一个具体事务，也可以通过Java形式对其进行描述，并封装成对象。其实就是Java对不正常情况进行描述后的对象体现。Java将异常封装成了一个对象。  异常的分类在Java程序设计语言中，异常对象都是派生于Throwable类的一个实例（即所有的异常类都继承于Throwable类）。如果Java中">
<meta property="og:locale" content="zh-Hans">
<meta property="og:image" content="http://yoursite.com/2019/04/11/Java语言-23-异常/异常的分类.png">
<meta property="og:updated_time" content="2019-04-27T15:28:14.163Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="23-异常">
<meta name="twitter:description" content="异常概述异常就是Java程序运行过程中出现的错误（通常有不同严重程度）。 异常由来：异常也是现实生活中的一个具体事务，也可以通过Java形式对其进行描述，并封装成对象。其实就是Java对不正常情况进行描述后的对象体现。Java将异常封装成了一个对象。  异常的分类在Java程序设计语言中，异常对象都是派生于Throwable类的一个实例（即所有的异常类都继承于Throwable类）。如果Java中">
<meta name="twitter:image" content="http://yoursite.com/2019/04/11/Java语言-23-异常/异常的分类.png">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Gemini',
    version: '5.1.4',
    sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: true,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="http://yoursite.com/2019/04/11/Java语言-23-异常/">





  <title>23-异常 | 新世纪Coder战士的博客</title>
  








</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-Hans">

  
  
    
  

  <div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">新世纪Coder战士的博客</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle"></p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br>
            
            首页
          </a>
        </li>
      
        
        <li class="menu-item menu-item-about">
          <a href="/about/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-user"></i> <br>
            
            关于
          </a>
        </li>
      
        
        <li class="menu-item menu-item-tags">
          <a href="/tags/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-tags"></i> <br>
            
            标签
          </a>
        </li>
      
        
        <li class="menu-item menu-item-categories">
          <a href="/categories/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-th"></i> <br>
            
            分类
          </a>
        </li>
      
        
        <li class="menu-item menu-item-archives">
          <a href="/archives/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br>
            
            归档
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-normal" itemscope itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="http://yoursite.com/2019/04/11/Java语言-23-异常/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="name" content="新世纪Coder战士">
      <meta itemprop="description" content>
      <meta itemprop="image" content="/images/caihong.png">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="新世纪Coder战士的博客">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">23-异常</h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">发表于</span>
              
              <time title="创建于" itemprop="dateCreated datePublished" datetime="2019-04-11T19:46:11+08:00">
                2019-04-11
              </time>
            

            

            
          </span>

          
            <span class="post-category">
            
              <span class="post-meta-divider">|</span>
            
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              
                <span class="post-meta-item-text">分类于</span>
              
              
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/做一个有骨气的Coder/" itemprop="url" rel="index">
                    <span itemprop="name">做一个有骨气的Coder</span>
                  </a>
                </span>

                
                
                  ， 
                
              
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/做一个有骨气的Coder/我的JavaEE哪有这么熟练/" itemprop="url" rel="index">
                    <span itemprop="name">我的JavaEE哪有这么熟练</span>
                  </a>
                </span>

                
                
                  ， 
                
              
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/做一个有骨气的Coder/我的JavaEE哪有这么熟练/Java语言/" itemprop="url" rel="index">
                    <span itemprop="name">Java语言</span>
                  </a>
                </span>

                
                
                  ， 
                
              
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/做一个有骨气的Coder/我的JavaEE哪有这么熟练/Java语言/入门篇/" itemprop="url" rel="index">
                    <span itemprop="name">入门篇</span>
                  </a>
                </span>

                
                
              
            </span>
          

          
            
          

          
          

          

          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <h1 id="异常概述"><a href="#异常概述" class="headerlink" title="异常概述"></a>异常概述</h1><p>异常就是Java程序运行过程中出现的错误（通常有不同严重程度）。</p>
<p>异常由来：异常也是现实生活中的一个具体事务，也可以通过Java形式对其进行描述，并封装成对象。其实就是Java对不正常情况进行描述后的对象体现。Java将异常封装成了一个对象。</p>
<hr>
<h1 id="异常的分类"><a href="#异常的分类" class="headerlink" title="异常的分类"></a>异常的分类</h1><p>在Java程序设计语言中，异常对象都是派生于Throwable类的一个实例（即所有的异常类都继承于Throwable类）。如果Java中内置的异常类不能够满足需求，用户还可以创建自己的异常类。Java异常层次结构的简化示意图如下：<br><img src="/2019/04/11/Java语言-23-异常/异常的分类.png" title="异常的分类"></p>
<p>需要注意的是，所有的异常都是由Throwable继承而来，但在下一层立即分解为两个分支：Error和Exception。然后在下一层Exception又被分解为两个分支：编译期异常（受检查异常）和运行时异常即RuntimeException（非受检查异常）。</p>
<p>所以，大致上可以把异常分为三类：</p>
<ol>
<li><p>ERROR：</p>
<ul>
<li><p>Error类层次结构描述了Java运行时系统的内部错误和资源耗尽错误。应用程序不应该抛出这种类型的对象，通常都是由虚拟机抛出的问题。如果出现了这样的内部错误，除了通告给用户，并尽力使程序安全地终止之外，再也无能为力了。这种情况很少出现。</p>
</li>
<li><p>例如：堆栈溢出异常（StackOverflowError）、内存溢出异常（OutOfMemoryError）等。</p>
</li>
</ul>
</li>
<li><p>编译期异常：</p>
<ul>
<li><p>除了RuntimeException及其子类，Exception中所有的子类都是，这种异常必须要处理，否则编译无法通过，推荐用try…catch进行处理。</p>
</li>
<li><p>例如：打印输出异常（PrintException）等。</p>
</li>
</ul>
</li>
<li><p>运行时异常（RuntimeError）：</p>
<ul>
<li><p>RuntimeException及其子类都是，这种异常不处理编译也会通过，不过这样的程序会有安全隐患，在运行时可能出错，遇到这种异常不推荐用try…catch进行处理，一般需要通过修改代码的逻辑来解决。</p>
</li>
<li><p>例如：空指针异常（NullPointerException）、数组越界异常（ArrayIndexOutOfBoundsException）、类型转换异常（ClassCastException）等。</p>
</li>
</ul>
<hr>
</li>
</ol>
<h1 id="JVM对异常的默认处理"><a href="#JVM对异常的默认处理" class="headerlink" title="JVM对异常的默认处理"></a>JVM对异常的默认处理</h1><p>如果我们没有对程序中的异常做出处理，JVM会对异常做出默认处理，处理流程如下：</p>
<ol>
<li>jvm发现了程序中的问题（例如：在程序中执行了1/0），java将这种常见的问题进行描述，并封装成对象（例如：1/0会被封装成一个ArithmeticException的对象）。</li>
<li>当问题发生后，jvm将该问题打包成了一个异常对象。</li>
<li>jvm将异常对象抛给调用者main函数，（例如：1/0的异常对象是new ArithmeticException(“/by zero”)）。</li>
<li>main函数收到这个问题时，有两种处理方式：一是可以自己将该问题处理，然后继续运行；二是如果自己没有针对的处理方式，只有交给调用main的jvm来处理。</li>
<li>jvm有一个默认的异常处理机制：首先在控制台打印出在哪个线程中发生了异常，异常的类型，异常的信息，异常的调用栈；然后终止程序。</li>
</ol>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        System.out.println(<span class="number">1</span>/<span class="number">0</span>);                        <span class="comment">//ERROR：ArithmeticException: / by zero</span></span><br><span class="line">	&#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>该代码的运行结果如下：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">Exception in thread &quot;main&quot; java.lang.ArithmeticException: / by zero</span><br><span class="line">        at ExceptionDemo.main(ExceptionDemo.java:3)</span><br></pre></td></tr></table></figure></p>
<hr>
<h1 id="异常的处理方案"><a href="#异常的处理方案" class="headerlink" title="异常的处理方案"></a>异常的处理方案</h1><p>对异常的处理有如下两种方案：</p>
<ol>
<li>try…catch：出现了问题，我自己解决掉。</li>
<li>throws：出现了问题，我自己解决不了，那我就抛给别人解决。</li>
</ol>
<h2 id="try…catch处理方案"><a href="#try…catch处理方案" class="headerlink" title="try…catch处理方案"></a>try…catch处理方案</h2><p><strong>注意</strong>：</p>
<ul>
<li>try里面的代码越少越好，最好只有可能发生异常的代码。</li>
</ul>
<h3 id="捕获单个异常"><a href="#捕获单个异常" class="headerlink" title="捕获单个异常"></a>捕获单个异常</h3><p>要想捕获一个异常，必须设置try/catch语句块。格式（伪代码）如下：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    要被检查的代码(可能发生异常的代码)</span><br><span class="line">&#125; <span class="keyword">catch</span> (异常类型 异常名) &#123;</span><br><span class="line">    捕获异常，并进行处理。处理完之后异常就不再存在</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>如果在try语句块中的任何代码抛出了一个在catch子句中说明的异常类，那么程序将跳过try语句块的其余代码，然后转去执行catch子句中的处理器代码，并且在执行完catch子句中的处理器代码后也不会再回去执行try语句块中未执行的代码。</p>
<p>之所以在执行完catch子句中的处理器代码后也不会再回去执行try语句块中未执行的代码，与Java的设计理念有关，Java认为代码前后之间是有关联的，前面的代码如果就有问题，那么后面的代码就不用再执行了，因为可能后面代码的执行会受到前面代码错误的影响。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                    <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">            System.out.println(<span class="string">"..."</span>);                  <span class="comment">//该语句不会被执行</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//捕获ArithmeticException异常</span></span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);               <span class="comment">//输出除0异常</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>如果在try语句块中的代码没有拋出任何异常，那么程序将跳过catch子句。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">1</span>);                    <span class="comment">//try语句块中没有异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//catch子句会被跳过</span></span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);               <span class="comment">//该语句不会被执行</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>如果方法中的任何代码拋出了一个在catch子句中没有声明的异常类型，那么这个方法就会立刻退出（希望调用者为这种类型的异常设计了catch子句）。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                    <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (PrintException e) &#123;                    <span class="comment">//catch中没有声明ArithmeticException异常，程序会立刻退出</span></span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<h3 id="捕获多个异常"><a href="#捕获多个异常" class="headerlink" title="捕获多个异常"></a>捕获多个异常</h3><p>在一个try语句块中可以捕获多个异常类型，并对不同类型的异常做出不同的处理。格式（伪代码）如下：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    要被检查的代码(可能发生异常的代码)</span><br><span class="line">&#125; <span class="keyword">catch</span> (异常类型 异常名) &#123;</span><br><span class="line">    捕获异常，并进行处理。处理完之后异常就不再存在</span><br><span class="line">&#125; <span class="keyword">catch</span> (异常类型 异常名) &#123;</span><br><span class="line">    捕获异常，并进行处理。处理完之后异常就不再存在</span><br><span class="line">......</span><br></pre></td></tr></table></figure></p>
<p>如果发生异常，异常对象会依次和catch子句进行匹配，如果匹配到了，程序就跳过try语句块的其余代码转去执行对应的catch子句，catch子句只会执行一个，并且执行完以后就会跳出整个try/catch语句块，不会再回去执行try语句块中未执行的代码。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                    <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">            System.out.println(<span class="number">2</span>/<span class="number">0</span>);                    <span class="comment">//尽管执行该语句也会抛出一个异常，但是该语句不会被执行，因为在执行该语句前就已经抛出了一个异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArrayIndexOutOfBoundsException e) &#123;    <span class="comment">//异常匹配失败</span></span><br><span class="line">            System.out.println(<span class="string">"数组越界异常"</span>);</span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//异常匹配成功，执行该catch子句，并在执行完以后跳出整个try/catch语句块</span></span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);               <span class="comment">//输出除0异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;                         <span class="comment">//匹配成功后不会再继续匹配</span></span><br><span class="line">            System.out.println(<span class="string">"其他异常"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>在Java SE 7中，同一个catch子句中可以捕获多个异常类型，不同异常类型之间用|符号分隔，即可以将若干个异常匹配放在一个catch子句中。只要在try语句块中抛出catch子句中能捕获的任何一个异常，都能被该catch子句成功匹配。</p>
<p>根据JDK7的新特性，在开发中，往往会对不同的异常进行同样处理。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                                          <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArrayIndexOutOfBoundsException | ArithmeticException e) &#123;    <span class="comment">//该catch子句可以捕获ArrayIndexOutOfBoundsException异常或ArithmeticException异常，这里捕获到了ArithmeticException异常</span></span><br><span class="line">            System.out.println(<span class="string">"数组越界异常或除0异常"</span>);                        <span class="comment">//输出数组越界异常或除0异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">            System.out.println(<span class="string">"其他异常"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>异常类型如果是不兼容的，谁先谁后没有关系，如果有兼容关系，例如：两个异常之间存在继承关系，父类异常应该位于子类异常后面。</p>
<p>之所以这样设计是因为，只要抛出的异常能在catch子句中被子类异常成功匹配，那么该异常就一定能被父类异常成功匹配，而catch子句只会执行一个，并且执行完以后就会跳出整个try/catch语句块，所以如果把匹配子类异常的catch子句放在匹配父类异常的catch子句后面，匹配子类异常的catch子句将永远不会被执行。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);</span><br><span class="line">            System.out.println(<span class="number">2</span>/<span class="number">0</span>);</span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;                         <span class="comment">//ERROR：Exception是ArithmeticException的父类，所以该catch子句应该放在匹配ArithmeticException异常的catch子句的后面</span></span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);</span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">            System.out.println(<span class="string">"其他异常"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<h3 id="finally-子句"><a href="#finally-子句" class="headerlink" title="finally 子句"></a>finally 子句</h3><p>当代码抛出一个异常时，就会终止方法中剩余代码的处理，并退出这个方法的执行。如果方法获得了一些本地资源，并且只有这个方法自己知道，又如果这些资源在退出方法之前必须被回收，那么就会产生资源回收问题。一种解决方案是捕获并重新抛出所有的异常。但是，这种解决方案比较乏味，这是因为需要在两个地方清除所分配的资源。一个在正常的代码中；另一个在异常代码中。Java有一种更好的解决方案，这就是finally子句。</p>
<p>不管是否有异常被捕获，finally子句中的代码都被执行。事实上，我们认为在需要关闭资源时，用这种方式使用finally子句是一种不错的选择。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                    <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//捕获ArithmeticException异常</span></span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);               <span class="comment">//输出除0异常</span></span><br><span class="line">        &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">            System.out.println(<span class="string">"finally"</span>);              <span class="comment">//输出finally</span></span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">1</span>);                    <span class="comment">//该try语句块中没有异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//该catch子句会被跳过</span></span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);               <span class="comment">//该语句不会被执行</span></span><br><span class="line">        &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">            System.out.println(<span class="string">"finally"</span>);              <span class="comment">//输出finally</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>只有在一种特殊情况下，finally子句中的代码不会被执行，那就是在执行到finally之前jvm退出了（比如程序中执行了System.exit(0)）。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.exit(<span class="number">0</span>);                             <span class="comment">//status是状态码，0表示正常退出</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;</span><br><span class="line">            System.out.println(<span class="string">"除0异常"</span>);</span><br><span class="line">        &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">            System.out.println(<span class="string">"finally"</span>);              <span class="comment">//该finally子句不会被执行，应为在执行到finally之前jvm退出了</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>如果catch子句里面有return语句，请问finally子句的代码还会执行吗？答案是会，其实finally子句的代码是在return中间执行的。具体执行顺序如下：</p>
<ol>
<li>执行catch语句块里面的return语句的时候，其实就已经生成了返回路径。</li>
<li>然后先不返回，转去执行finally子句，执行完以后再按照原来生成的返回路径返回。</li>
</ol>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">int</span> result = method();</span><br><span class="line">        System.out.println(<span class="string">"result = "</span> + result);       <span class="comment">//输出result = 30</span></span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">int</span> <span class="title">method</span><span class="params">()</span> </span>&#123;</span><br><span class="line">        <span class="keyword">int</span> result = <span class="number">10</span>;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                    <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">            result = <span class="number">20</span>;                                <span class="comment">//该语句不会被执行，因为执行之前已经抛出了一个异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//捕获ArithmeticException异常</span></span><br><span class="line">            result = <span class="number">30</span>;                                <span class="comment">//result = 30</span></span><br><span class="line">            <span class="keyword">return</span> result;                              <span class="comment">//先生成返回路径，然后转去执行finally子句，等finally子句执行完以后再按照原来生成的返回路径返回，在原来的返回路径里要返回的result的一个拷贝值还是30，并没有更新成40</span></span><br><span class="line">        &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">            result = <span class="number">40</span>;                                <span class="comment">//result = 40</span></span><br><span class="line">        &#125;</span><br><span class="line">        <span class="keyword">return</span> result;                                  <span class="comment">//该语句不会被执行，因为执行之前已经return了</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>如果finally子句里面也有return语句，因为finally子句里的代码一定会被执行，所以就会新生成一条新的返回路径去覆盖原来catch子句里面生成的返回路径。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">int</span> result = method();</span><br><span class="line">        System.out.println(<span class="string">"result = "</span> + result);       <span class="comment">//输出result = 40</span></span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">int</span> <span class="title">method</span><span class="params">()</span> </span>&#123;</span><br><span class="line">        <span class="keyword">int</span> result = <span class="number">10</span>;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                    <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">            result = <span class="number">20</span>;                                <span class="comment">//该语句不会被执行，因为执行之前已经抛出了一个异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//捕获ArithmeticException异常</span></span><br><span class="line">            result = <span class="number">30</span>;                                <span class="comment">//result = 30</span></span><br><span class="line">            <span class="keyword">return</span> result;                              <span class="comment">//先生成返回路径，然后转去执行finally子句</span></span><br><span class="line">        &#125; <span class="keyword">finally</span> &#123;</span><br><span class="line">            result = <span class="number">40</span>;                                <span class="comment">//result = 40</span></span><br><span class="line">            <span class="keyword">return</span> result;                              <span class="comment">//这里新生成返回路径会覆盖原来catch子句里面生成的返回路径，在新的返回路径里要返回的result的一个拷贝值是40</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<h2 id="throws处理方案"><a href="#throws处理方案" class="headerlink" title="throws处理方案"></a>throws处理方案</h2><p>定义功能方法时，可以把出现的问题暴露出来让调用者去处理。那么就通过throws在方法上标识。</p>
<p>如果抛出的是运行时异常，上级可以处理也可以不处理，但是如果不处理程序在运行时可能会出错；如果抛出的是编译期异常，上级必须处理，否则编译不能通过，或者上级也可以继续往上抛给更上一级，但是必须有一级要对该异常做出处理，如果最后到了main函数还是没处理继续往上抛，就会抛给JVM，然后JVM会做出默认处理。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> java.text.SimpleDateFormat;</span><br><span class="line"><span class="keyword">import</span> java.text.ParseException;</span><br><span class="line"><span class="keyword">import</span> java.util.Date;</span><br><span class="line"></span><br><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> <span class="keyword">throws</span> ParseException </span>&#123;    <span class="comment">//通过throws在方法上标识以便把异常抛给上一级，这里是抛给JVM来处理</span></span><br><span class="line">        <span class="keyword">final</span> String format = <span class="string">"yyyy-MM-dd"</span>;</span><br><span class="line">        String time = <span class="string">"2019-01-01"</span>;</span><br><span class="line">        SimpleDateFormat sdf = <span class="keyword">new</span> SimpleDateFormat(format);</span><br><span class="line">        Date date = sdf.parse(time);                    <span class="comment">//这里会抛出一个ParseException异常，这是一个编译期异常，如果不处理无法通过编译，可以用try/catch或throws两种方案处理</span></span><br><span class="line">        System.out.println(date);                       <span class="comment">//输出Tue Jan 01 00:00:00 CST 2019</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<hr>
<h1 id="抛出异常"><a href="#抛出异常" class="headerlink" title="抛出异常"></a>抛出异常</h1><p>在功能方法内部出现某种情况，程序不能继续运行，需要进行跳转时，就用throw把异常对象抛出。throw用在方法体内，跟的是一个具体的异常对象，且只能抛出一个异常。</p>
<p>对于throw（自己人为抛出）的异常，也同样有try/catch和throws两种方案来处理。</p>
<p>可以把抛出异常的语句写在try子句里，然后通过catch子句来捕获处理。</p>
<p>下面给出一个的例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> Exception();                      <span class="comment">//人为抛出一个异常对象，并捕获和处理该异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">            System.out.println(<span class="string">"异常"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<p>当然一般情况下，throw（自己人为抛出）的异常往往是直接抛给上一级的，让上一级或者是更上一级来处理，即用throws的方案来处理异常。这时候还需要通过throws在方法上标识。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;                                           <span class="comment">//在抛出异常的方法的上一级处理异常，如果在这一级也不给出异常捕获与处理，可以继续在这一级往上抛，只要继续通过throws在这一级的方法上标识，就可以继续抛给上一级</span></span><br><span class="line">            method();</span><br><span class="line">        &#125; <span class="keyword">catch</span> (Exception e) &#123;</span><br><span class="line">            System.out.println(<span class="string">"异常"</span>);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">method</span><span class="params">()</span> <span class="keyword">throws</span> Exception </span>&#123;      <span class="comment">//通过throws在方法上标识以便把异常抛给上一级</span></span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> Exception();                          <span class="comment">//人为抛出一个异常对象</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<hr>
<h1 id="所有异常的父类Throwable"><a href="#所有异常的父类Throwable" class="headerlink" title="所有异常的父类Throwable"></a>所有异常的父类Throwable</h1><p>所有异常都继承自Exception类，而Exception类又继承自Throwable类，所以所有的异常都继承了Throwable类中的方法。下面列出了Throwable类提供的一些常用API，通过这些方法，我们可以获得异常的相关信息：</p>
<table>
<thead>
<tr>
<th>方法</th>
<th>功能</th>
</tr>
</thead>
<tbody>
<tr>
<td>public String getMessage()</td>
<td>返回此异常的详细消息字符串</td>
</tr>
<tr>
<td>public String toString()</td>
<td>返回此异常的简短描述</td>
</tr>
<tr>
<td>public void printStackTrace()</td>
<td>将此异常及其追踪输出至标准错误流（即控制台）</td>
</tr>
<tr>
<td>public void printStackTrace(PrintStream s)</td>
<td>将此异常及其追踪输出到指定的输出流（通常用该方法将异常内容保存在日志文件中，以便查阅）</td>
</tr>
</tbody>
</table>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            System.out.println(<span class="number">1</span>/<span class="number">0</span>);                    <span class="comment">//这里会抛出一个ArithmeticException异常</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//捕获ArithmeticException异常</span></span><br><span class="line">            e.printStackTrace();                        <span class="comment">//将异常及其追踪输出至标准错误流</span></span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<hr>
<h1 id="自定义异常"><a href="#自定义异常" class="headerlink" title="自定义异常"></a>自定义异常</h1><p>在程序中，可能会遇到任何标准异常类都没有能够充分地描述清楚的问题。在这种情况下，就可以定义自己的异常类了。我们需要做的只是定义一个派生于Exception的类，或者派生于Exception子类的类。</p>
<p>对于异常，其实类名就提示了异常信息。所以可以在定义自己的异常类的时候，可以取一个能提示异常信息的类名。</p>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">int</span> score = <span class="number">101</span>;</span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            check(score);</span><br><span class="line">        &#125; <span class="keyword">catch</span> (ScoreException e) &#123;</span><br><span class="line">            e.printStackTrace();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">private</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">check</span><span class="params">(<span class="keyword">int</span> score)</span> <span class="keyword">throws</span> ScoreException </span>&#123;</span><br><span class="line">        <span class="keyword">if</span> (score &lt; <span class="number">0</span> || score &gt; <span class="number">100</span>) &#123;                 <span class="comment">//只要输入的分数不合法（即不在0~100之间），就会抛出一个分数异常</span></span><br><span class="line">            <span class="keyword">throw</span> <span class="keyword">new</span> ScoreException(<span class="string">"score="</span> + score);</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">ScoreException</span> <span class="keyword">extends</span> <span class="title">Exception</span> </span>&#123;                <span class="comment">//定义一个分数异常类，继承自Exception类</span></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="title">ScoreException</span><span class="params">()</span> </span>&#123;</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="title">ScoreException</span><span class="params">(String message)</span> </span>&#123;</span><br><span class="line">        <span class="keyword">super</span>(message);</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>
<hr>
<h1 id="异常的处理原则"><a href="#异常的处理原则" class="headerlink" title="异常的处理原则"></a>异常的处理原则</h1><ol>
<li>自己处理：<ul>
<li>如果异常在该方法能够处理，那就自己处理（及早处理）。</li>
<li>如果异常后面的代码还要执行，只能自己处理，因为如果抛给上级处理，该方法一定会处于某个上级的try语句块中，一旦上级捕获并处理完异常，就不会再回去执行try语句块中未执行的代码，这样异常后面的代码自然就无法被执行了。</li>
</ul>
</li>
<li>抛给上级处理：<ul>
<li>如果自己处理不了就往上抛。</li>
<li>如果异常后面的代码不需要执行，就可以往上抛。</li>
</ul>
</li>
</ol>
<hr>
<h1 id="异常的注意事项"><a href="#异常的注意事项" class="headerlink" title="异常的注意事项"></a>异常的注意事项</h1><ol>
<li><p>子类重写父类方法时，子类的方法必须抛出相同的异常或父类异常的子类。</p>
</li>
<li><p>如果父类抛出了多个异常，子类重写父类时，只能抛出相同的异常或者是他的子集，子类不能抛出父类没有的异常。</p>
</li>
<li><p>如果被重写的方法没有异常抛出，那么子类的方法绝对不可以抛出异常，如果子类方法内有异常发生，那么子类只能try，不能throws。</p>
</li>
</ol>
<p>下面给出一个例子：<br><figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="class"><span class="keyword">class</span> <span class="title">ExceptionDemo</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">static</span> <span class="keyword">void</span> <span class="title">main</span><span class="params">(String[] args)</span> </span>&#123;</span><br><span class="line">        Father father = <span class="keyword">new</span> Son();                      <span class="comment">//多态：父类引用子类的对象</span></span><br><span class="line">        <span class="keyword">try</span> &#123;</span><br><span class="line">            father.method();                            <span class="comment">//ERROR：抛出的ArrayIndexOutOfBoundsException异常在catch中无法成功匹配</span></span><br><span class="line">        &#125; <span class="keyword">catch</span> (ArithmeticException e) &#123;               <span class="comment">//程序在设计时是按照父类方法抛出的异常来处理的，但是按照多态的成员访问特点：编译看左边，运行看右边，程序在执行的时候，抛出的是子类方法抛出的异常，所以该程序编译的时候没问题，但是执行的时候就会出问题</span></span><br><span class="line">            e.printStackTrace();</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Father</span> </span>&#123;</span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">method</span><span class="params">()</span> <span class="keyword">throws</span> ArithmeticException </span>&#123;</span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> ArithmeticException();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="class"><span class="keyword">class</span> <span class="title">Son</span> <span class="keyword">extends</span> <span class="title">Father</span></span>&#123;</span><br><span class="line">    <span class="meta">@Override</span></span><br><span class="line">    <span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">method</span><span class="params">()</span> <span class="keyword">throws</span> ArrayIndexOutOfBoundsException </span>&#123;    <span class="comment">//这里子类重写父类方法时，子类方法抛出的异常和父类方法抛出的异常不同，且也不是父类方法抛出异常的子类</span></span><br><span class="line">        <span class="keyword">throw</span> <span class="keyword">new</span> ArrayIndexOutOfBoundsException();</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure></p>

      
    </div>
    
    
    

    

    

    

    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/tags/IT/" rel="tag"># IT</a>
          
        </div>
      

      
      
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2019/04/05/Java语言-22-Object类/" rel="next" title="22-Object类">
                <i class="fa fa-chevron-left"></i> 22-Object类
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2019/04/13/Java语言-24-泛型/" rel="prev" title="24-泛型">
                24-泛型 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </div>
  
  
  
  </article>



    <div class="post-spread">
      
    </div>
  </div>


          </div>
          


          

  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <img class="site-author-image" itemprop="image" src="/images/caihong.png" alt="新世纪Coder战士">
            
              <p class="site-author-name" itemprop="name">新世纪Coder战士</p>
              <p class="site-description motion-element" itemprop="description">这个人很宅。</p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/archives/">
              
                  <span class="site-state-item-count">49</span>
                  <span class="site-state-item-name">日志</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-categories">
                <a href="/categories/index.html">
                  <span class="site-state-item-count">18</span>
                  <span class="site-state-item-name">分类</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-tags">
                <a href="/tags/index.html">
                  <span class="site-state-item-count">2</span>
                  <span class="site-state-item-name">标签</span>
                </a>
              </div>
            

          </nav>

          

          
            <div class="links-of-author motion-element">
                
                  <span class="links-of-author-item">
                    <a href="https://github.com/AI39" target="_blank" title="GitHub">
                      
                        <i class="fa fa-fw fa-github"></i>GitHub</a>
                  </span>
                
            </div>
          

          
          

          
          

          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#异常概述"><span class="nav-number">1.</span> <span class="nav-text">异常概述</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#异常的分类"><span class="nav-number">2.</span> <span class="nav-text">异常的分类</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#JVM对异常的默认处理"><span class="nav-number">3.</span> <span class="nav-text">JVM对异常的默认处理</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#异常的处理方案"><span class="nav-number">4.</span> <span class="nav-text">异常的处理方案</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#try…catch处理方案"><span class="nav-number">4.1.</span> <span class="nav-text">try…catch处理方案</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#捕获单个异常"><span class="nav-number">4.1.1.</span> <span class="nav-text">捕获单个异常</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#捕获多个异常"><span class="nav-number">4.1.2.</span> <span class="nav-text">捕获多个异常</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#finally-子句"><span class="nav-number">4.1.3.</span> <span class="nav-text">finally 子句</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#throws处理方案"><span class="nav-number">4.2.</span> <span class="nav-text">throws处理方案</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#抛出异常"><span class="nav-number">5.</span> <span class="nav-text">抛出异常</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#所有异常的父类Throwable"><span class="nav-number">6.</span> <span class="nav-text">所有异常的父类Throwable</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#自定义异常"><span class="nav-number">7.</span> <span class="nav-text">自定义异常</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#异常的处理原则"><span class="nav-number">8.</span> <span class="nav-text">异常的处理原则</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#异常的注意事项"><span class="nav-number">9.</span> <span class="nav-text">异常的注意事项</span></a></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2019</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">新世纪Coder战士</span>

  
</div>


  <div class="powered-by">由 <a class="theme-link" target="_blank" href="https://hexo.io">Hexo</a> 强力驱动</div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">主题 &mdash; <a class="theme-link" target="_blank" href="https://github.com/iissnan/hexo-theme-next">NexT.Gemini</a> v5.1.4</div>




        







        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  












  
  
    <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>
  

  
  
    <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>
  

  
  
    <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>
  


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.4"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.4"></script>



  
  


  <script type="text/javascript" src="/js/src/affix.js?v=5.1.4"></script>

  <script type="text/javascript" src="/js/src/schemes/pisces.js?v=5.1.4"></script>



  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.4"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.4"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.4"></script>



  


  




	





  





  












  





  

  

  

  
  

  

  

  

<script src="/live2dw/lib/L2Dwidget.min.js?0c58a1486de42ac6cc1c59c7d98ae887"></script><script>L2Dwidget.init({"pluginRootPath":"live2dw/","pluginJsPath":"lib/","pluginModelPath":"assets/","tagMode":false,"log":false,"model":{"jsonPath":"/live2dw/assets/koharu.model.json"},"display":{"position":"right","width":75,"height":150},"mobile":{"show":true}});</script></body>
</html>
